### ISSUE TITLE
change name maybe?

### ISSUE THREAD

**Issue by DanNBullock** [DSPG-Young-Scholars-Program/DSPG2020_ARI2#16]
https://github.com/DSPG-Young-Scholars-Program/DSPG2020_ARI2/blob/56aba08eedf80031a50d402bce1da3a230ea7f32/src/lda/performance_tidy_text.Rmd#L29

Apparently it doesn't like it when you reuse chunk names.  I suspect that this was supposed to be named read_library anyways.

**Comment by lizhmil** [comment]
done
