### ISSUE TITLE
library readxl

### ISSUE THREAD

**Issue by DanNBullock** [DSPG-Young-Scholars-Program/DSPG2020_ARI2#9]
https://github.com/DSPG-Young-Scholars-Program/DSPG2020_ARI2/blob/e51b582b4613d639ebd615f124d345b7b8dfd716/src/lda/performance_tidy_text.Rmd#L32

I think you need this here  

https://github.com/DSPG-Young-Scholars-Program/DSPG2020_ARI2/blob/e51b582b4613d639ebd615f124d345b7b8dfd716/src/lda/performance_lda.Rmd#L19

**Comment by lizhmil** [comment]
Yes I do! Thanks!
